name: acdc
description: Dart client for generating an `ACDC` object from provided id, data and schema.
version: 1.1.0
homepage: https://github.com/THCLab/acdc-bindings/tree/main/bindings/dart/acdc

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.82.1
  meta: ^1.8.0
  plugin_platform_interface: ^2.0.2
  uuid: ^3.0.7

dev_dependencies:
  ffigen: ^8.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.thclab.acdc
        pluginClass: AcdcPlugin
      ios:
        pluginClass: AcdcPlugin
      windows:
        pluginClass: AcdcPluginCApi
      macos:
        pluginClass: AcdcPlugin

